activation_days: 7
apps:
  - client_id: gdrgdhgnjsdfsefs
    client_secret: soinfosienesfseff3298zhiub9328ruoisnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.arkitekt
    name: Arkitekt Test Client
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
      - write
    tenant: admin
    version: latest
    token: 293j40239j4023023n09nj09n49nin3w30d9n203nf03f
  - client_id: snfoinosinefsef
    client_secret: 9noinfpuisenfpsiuenfpiosenfiusef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.orkestrator
    name: orkestrator
    redirect_uris:
      - http://127.0.0.1/
      - http://127.0.0.1/callback
      - http://localhost:8010/callback
      - http://localhost:8010/
    scopes:
      - read
      - write
    tenant: admin
    version: latest
    token: 293j40239j4023023n039j30sdofins3n09nw30d9n203nf03fsdfseoinsoeinfosein
  - client_id: soinfosienfsfosefghsegfisnefoisneofinsef
    client_secret: soinfoefsefssdfienfoisnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.doks
    name: doks
    redirect_uris:
      - http://127.0.0.1/
      - https://arkitekt.live
      - https://arkitekt.live/callback
    scopes:
      - read
      - write
    tenant: admin
    version: latest
    token: 293j40239j4023023n09nw3oinfinoifnsoifnosineoifnsef0d9n203nf03f
  - client_id: soinfosienfoaswdasdasdisnefoisneofinsef
    client_secret: soinfosiengeesegegfoisnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikromanager
    name: MikroManager
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
      - write
    tenant: admin
    version: latest
    token: 304n03940p39m4f09o304fo9m0394mf039n4f039n4f093n4f
  - client_id: soinfosienfoissgsegsegtbsynefoisneofinsef
    client_secret: soinfosienfoissdfsdfnefoisneofinsef
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikro-napari
    name: napari
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
      - write
    tenant: admin
    version: latest
    token: 093j4093n4f09m3094mf09m309mf09mf094n09enf09n23
  - client_id: sdfsfshrhsdbse4gsrgs4rgdrgsrdgedrg
    client_secret: ffesefnoweirnw9oinr0wnrosienfoin
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikroj
    name: mikroj
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
    tenant: admin
    version: v0.0.1
    token: 0394mr039m4f093m40f90934nf09n309m2039d029n3f092n3f0293fn
  - client_id: fsefgsdfoina9oiwendaosinaswdaw
    client_secret: ffesefnoweirnw9fesoienfspieounfspoeinoinr0wnrosienfoin
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.gucker
    name: gucker
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
    tenant: admin
    version: latest
    token: 2039rn0293md02m3f0pm2p30omr02oin3f0ß92m30f9n2039fn2039fn
  - client_id: fsdfsefsesef234234e2fd3dasdasd
    client_secret: ffesefnoweirnw9fesoienfspie23423sasdasdounfspoeinoinr0wnrosienfoin
    client_type: public
    grant_type: authorization-code
    identifier: github.io.jhnnsrs.mikro-manager
    name: mikro-manager
    redirect_uris:
      - http://127.0.0.1/
    scopes:
      - read
    tenant: admin
    version: "0.0.1"
    token: 4234234234u9381892huin9s8nef98n398nw398n29384n234


db:
  db_name: lok_db
  engine: django.db.backends.postgresql
  host: db
  password: d34567c83f0d5c0cf902b1f113f3771c
  port: 5432
  username: shabbychestnutlemur
deployment:
  name: paper
django:
  admin:
    password: admin
    username: admin
  debug: false
  hosts:
    - "*"
  secret_key: 7c3e115e5ca002eb4ca86aaca7419bd6
groups: 
  - name: mygroup
    description: mygroup
minio:
  access_key: snappyvioletcockroach
  buckets:
    media: lokmedia
  host: minio
  port: "9000"
  protocol: http
  secret_key: 5a1bbb00b441e743283330828d90c515
private_key:  |
  -----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNDA3Ru8CluXQb
  xmszu31SzUqTrhKF1m6/H2fGpQqc8v+vXshFHMdGIy5IjASydP945pBZXxLcDfbk
  eFiSQBgVYto3s2ec9fmu8GGpEMaszq2cy09wEY/kitBt/fm8ZD7rTIEGTR3UJOJs
  R/4VZxHF8RTEUpXTl1adfZLQTW5AhCfniMQRDOQIq29nkoejPdJsKYq28iUJJhAI
  E7JwaVdmk3pvTGCXx1Hcn0TGutPC+TfmcQO9txBvSJCgJRacExmUQ7eQjMZ6wcZF
  rQ9eVMi6Knu7CryoWc8+qV9ELNvm08lv6OPu3giVyrGLzyudBVoXBRZ3Ju8THsXG
  xwfsf0ArAgMBAAECggEACp3bGm33gaC5nOc2TWrMejId8FfkJqDdnk0nz1ac1x6F
  KSNtCJhiXMSyjYK5GReufe82MAX8HypdtenhflpjGixe8qgkvYZ/GP+pXe/77eVo
  gpn2Rl+xhcUxGW4tn8qPaPzrIKKP4IoJB92uLAdoi1ePdsKRdmGQxiEYSmtP7HdB
  wXKw2EftURyMJyYbZj6rAJ/wCeJrAx4Lv+NEbqyudj6UNqTXUuKG52PuGRFuLX7L
  tLs9kKD0dNepGnWH6Ay6K9OFALgW8HVeAtk3Q3a7pBjl6XpK20CH0jNN0F1I/3vB
  +ulQg9sCZ0nZyKacfw1moLQOMmoPj8Zd0X2OVrLiIQKBgQDl+grt5wBWIl/sM1LH
  AmIJSZX6bKvYNy3ug13uAuw0nPqKLJn34Vk6WV3RKT3MiTQng+bFOsKzXATuSyG3
  3D0w+HgfyEVKobvaY9m7Z+VUyElQonVw4UvL1ffvAY+kO7cDRdvuNgUy1s5Epxhy
  g07RYmBOhcwCv38JvJEOIpRIYQKBgQDkP9mt41elgZjIwaGOjKSeNOr4F7FzLR37
  8buQmkBqKqbwzAZTSmb/1X40jqyaEJnIN5mdz3pJJfto3moiTgk8PNO/3dt/+x38
  ZXT3Ev/Re29S4GeJEEBqnm/gkeoQCDPjOw7AOnPY3wjRWJTjYec6OWSsoWMFxZYi
  NZIkgQKkCwKBgAztdVfSOG6fGA1LBUgylhg3jrq5CR/qWiaiM9GBUI3UlTDXOQB6
  Jm3lQCTV0KeCvu/Jtls35mH2tkA+8PJI6xepn/cJZvu/A7RPEJo8SOPvLk/eEgP6
  ZixbJsjEqbJtuOfyMV6+oqQs9wNc8T7eqruScB953fH5mcaOVwkYYIWBAoGBAK4U
  IHHlhNAeoibivtOYYmii1V33vAeqrkab28ByVJRkCUR3Zo+ZnCqcag+tjOhHpvGz
  rf5U4d/uDuuxTeLx/0so3RplG2ZlYD5CJs3VeLQM3x+nNG+trGNkiNEOmCQ4DVLN
  lPd43SfXGsOHOq6c2Zxnb2fWAk7Bnjpi/x3GIvx3AoGAd/G09zHICcZ4P7m+ykKf
  Wcb0JMz6ekEwHFJAUd4C5zj6fndvKJI8wSZziiIgwUAzLoGBLEZJg3nN8yuXzgqH
  9i+SDHaCW8wtZCXITuMrE4pnhQIgaS/E7XuaQtTnfjT7ibzwGlCgrJFJQ1ZFvUbo
  q+Pk+4XQVIwnAvKD+xjye7c=
  -----END PRIVATE KEY-----

public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNDA3Ru8CluXQbxmszu31SzUqTrhKF1m6/H2fGpQqc8v+vXshFHMdGIy5IjASydP945pBZXxLcDfbkeFiSQBgVYto3s2ec9fmu8GGpEMaszq2cy09wEY/kitBt/fm8ZD7rTIEGTR3UJOJsR/4VZxHF8RTEUpXTl1adfZLQTW5AhCfniMQRDOQIq29nkoejPdJsKYq28iUJJhAIE7JwaVdmk3pvTGCXx1Hcn0TGutPC+TfmcQO9txBvSJCgJRacExmUQ7eQjMZ6wcZFrQ9eVMi6Knu7CryoWc8+qV9ELNvm08lv6OPu3giVyrGLzyudBVoXBRZ3Ju8THsXGxwfsf0Ar
redis:
  host: redis
  port: 6379
scopes:
  can_assign: Can Assign Nodes
  can_create: Can Create Nodes
  can_create_identifier: Can create new identifier for the platform
  can_forward_bounce:
    Can reserve and assign to Nodes mimicking other Users (only
    backend and admin)
  can_provide: Can Provide Nodes
  can_template: Can Template Nodes
  introspection: Introspect the Token scope
  provider: Can act as a provider
  read: Reading all of your Data
  write: Writing to all of your Data
  read_starred: Reading all of your shared Data
token_expire_seconds: 604800
users: 
  - username: demo
    password: demo
    groups: 
      - mygroup 
