db:
  db_name: mikro_db
  engine: django.db.backends.postgresql
  host: db
  password: 729b57e27b27aa315f99db185033bde0
  port: 5432
  username: queasymaroonretriever
django:
  admin:
    password: admin
    username: admin
  debug: false
  hosts:
  - '*'
  secret_key: f62c393123db86c57c90b9d77865496a
lok:
  issuer: lok
  key_type: RS256
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7OBffVnKNC/qh0E1UhKWonUpZ0VeE8t7R+p7BYDEcUYpydFKoWpLu6YOeLeHcW0kbnr+DGJcMJTf1vT+NJ4FUguitEiS8n/DXfZd5v067lWLZUt1+RUDVnNRsNNuBOgpJo+bSuusvhrwxI/RDkVneSOGQet0fEYqyoenAyJOaByMwOmC1LJVFaYkYndEF3HhAt/BurmqS1dlh7COFJhxkN70/AVHdMuEOjoFDrHTU5lzyP/OJDH+zmzCjZ5+qg46SqeRPfQji0fzNxdgrbd0jlRPEnU65MIk1Q012IlwTfbtobm7kg6S3iKYT6bstRd5ubCO65E/n44zdwCSdCQN3
minio:
  access_key: surlyredtermite
  buckets:
    zarr: zarr
    parquet: parquet
    media: mikromedia
  host: minio
  port: '9000'
  protocol: http
  secret_key: d2be4084f4d9df763981cc63febc2676
redis:
  host: redis
  port: 6379