buckets:
  - name: flussmedia
  - name: lokmedia
  - name: lokmedia
  - name: lokmedia
  - name: zarr
  - name: parquet
  - name: mikromedia
  - name: lokmedia
  - name: portmedia
  - name: mikromedianew
  - name: zarrnew
  - name: parquetnew
users: 
  - access_key: shaggyviridiancat
    name: lok
    policies:
      - readwrite
    secret_key: 94c770e06665098a83e4d81155ecdd3b
  - access_key: scalylilacdachsbracke
    name: fluss
    policies:
      - readwrite
    secret_key: f11ac9f3969d3d859e3cda3c34ff3740
  - access_key: gamyochrevole
    name: minio
    policies:
      - readwrite
    secret_key: 6df2a289e2acc9c8989c830e4c931012
  - access_key: pokeysapphireurchin
    name: mikro
    policies:
      - readwrite
    secret_key: cdfba6fb5c7a12d6d0e37bc654aa9a27
  - access_key: jumpybistrechicken
    name: port
    policies:
      - readwrite
    secret_key: e47996e8397bd8310b93f478e08afda7
  - access_key: baggycinnamongerbil
    name: rekuest
    policies:
      - readwrite
    secret_key: ae5dae6fc2edecb3f4375c8f903aac82