buckets:
  - name: flussmedia
  - name: lokmedia
  - name: lokmedia
  - name: lokmedia
  - name: zarr
  - name: parquet
  - name: mikromedia
  - name: lokmedia
  - name: portmedia
  - name: mikromedianew
  - name: zarrnew
  - name: parquetnew
users: 
  - access_key: gummymaroonbulldog
    name: lok
    policies:
      - readwrite
    secret_key: af461be56ed28a15ec7888504bb4980c
  - access_key: muggyturquoiseopossum
    name: fluss
    policies:
      - readwrite
    secret_key: 5b84af04c935d463b55365cb03068bb6
  - access_key: shabbylilacopossum
    name: minio
    policies:
      - readwrite
    secret_key: 48d4b1d0e5089661f0c4f0271a4602db
  - access_key: surlyredtermite
    name: mikro
    policies:
      - readwrite
    secret_key: d2be4084f4d9df763981cc63febc2676
  - access_key: wheezygoldkakapo
    name: port
    policies:
      - readwrite
    secret_key: 3e1f8d276980ea16cd195664fba26137
  - access_key: flimsycharcoalgorilla
    name: rekuest
    policies:
      - readwrite
    secret_key: f65a15252bf1d809605641993d97b8d9