db:
  db_name: port_db
  engine: django.db.backends.postgresql
  host: db
  password: 44a93803b01ccf167ce339ad2418b9b3
  port: 5432
  username: flimsyazuresetter
django:
  admin:
    password: admin
    username: admin
  debug: false
  hosts:
  - '*'
  secret_key: 7bb0d033308724343f8aaf6a9d9ffdc9
lok:
  issuer: lok
  key_type: RS256
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZkdM9SuAqu/wNDFrfHmXv7ddH9YuOwJ9/eLXXDhtn2Izr+lDrcZb+r8Arx6GqeyFhUZOadr7xre+PorETL5aFZNq0sR9ysUiGYguEmyzlgeL/AEuj/Qg0IOK3cpQQ38LMRSZ/WuFcP/3p1CkB+U6DR1KORt1RvpnWXj3bfVVRvgALV7zdlB1LR0lyPTtvAnWAB3QTlIV8UU4CEe0VfZO1A947r9UwahgmTpZxGKNuZ65hPL3a4wa2/SE4OLiWxnkzLtcErSLvCI6ng00vlCi5pXG7IXX0QzmzLwuu2YouhqU7LAwmNNTLUcTP7a/hAd7dzP3c5jhkOhP/2WGqNfdb
minio:
  access_key: jumpybistrechicken
  buckets:
   media: portmedia
  host: minio
  port: '9000'
  protocol: http
  secret_key: e47996e8397bd8310b93f478e08afda7
redis:
  host: redis
  port: 6379
virtualizer:
  engine: docker